sonar.organization=toms56
sonar.projectKey=Toms56_WAMT
sonar.sources=.

# Exclut androidTest de la détection de duplication de code
sonar.cpd.exclusions=app/src/androidTest/**

# Optionnel : exclut androidTest des règles de Code Smells également
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S1192
sonar.issue.ignore.multicriteria.e1.resourceKey=app/src/androidTest/**